version: 2
jobs:
  unit test:
    docker:
      - image: cimg/node:lts
        environment:
          TZ: "Europe/London"
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package.json" }}
            - v1-deps-
      - run:
          name: install
          command: npm install
      - save_cache:
          key: v1-deps-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: test
          command: npm test
      - run:
          name: codecov
          command: npm run coverage
  lint:
    docker:
      - image: cimg/node:lts
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install standard
          command: npm install
      - run:
          name: lint
          command: npm run lint
  release:
    docker:
      - image: cimg/node:lts
        environment:
          TZ: "Europe/London"
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package.json" }}
            - v1-deps-
      - run:
          name: install
          command: npm install
      - save_cache:
          key: v1-deps-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: release
          command: npx semantic-release
workflows:
  version: 2
  test_and_release:
    jobs:
    - unit test:
        context: tymly_global
    - lint
    - release:
        context: tymly_global
        requires:
        - unit test
        - lint
        filters:
          branches:
            only: master
